openapi: 3.0.0
info:
  title: Horoscope API
  version: 1.0.0
  description: Horoscope App API for registration, login, and horoscope retrieval

servers:
  - url: http://localhost:3000/api

paths:
  /user/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        201:
          description: User registered successfully
        400:
          description: Email already in use

  /user/login:
    post:
      summary: Login a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        200:
          description: Login successful
        400:
          description: Invalid credentials

  /user/horoscope/today:
    get:
      summary: Get today's horoscope
      tags: [Horoscope]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Horoscope for today
        401:
          description: Unauthorized

  /user/horoscope/history:
    get:
      summary: Get 7-day horoscope history
      tags: [Horoscope]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Horoscope history
        401:
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterUser:
      type: object
      required: [name, email, password, birthdate]
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        birthdate:
          type: string
          format: date

    LoginUser:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
